# Generated by Django 5.1.4 on 2025-01-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('reporting_manager', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mode_of_work', models.CharField(choices=[('Work from office', 'Work from office'), ('Work from home', 'Work from home')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Holiday', 'Holiday'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=50)),
                ('sub_status', models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('Absent', 'Absent')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.employee')),
            ],
        ),
    ]
