# Generated by Django 5.1.4 on 2025-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0002_role_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action', models.CharField(default='Open Time Sheet', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
