# Generated by Django 5.1.4 on 2025-01-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
