# Generated by Django 5.1.4 on 2025-01-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0005_remove_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Holiday', 'Holiday'), ('Weekday', 'Weekday'), ('Leave', 'Leave')], max_length=50)),
                ('mode_of_work', models.CharField(choices=[('Remote', 'Remote'), ('Office', 'Office'), ('Field', 'Field')], max_length=50)),
                ('sub_status', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.employee')),
            ],
        ),
    ]
