# Generated by Django 5.1.4 on 2025-01-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0006_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager_email',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='mode_of_work',
            field=models.CharField(choices=[('work-form-home', 'work-form-home'), ('work-from-Office', 'work-from-Office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Weekday', 'Weekday'), ('weekend', 'weekend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='sub_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave')], default='Present', max_length=55),
        ),
    ]
