# Generated by Django 5.1.4 on 2025-01-08 10:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0009_alter_timesheet_date_alter_timesheet_mode_of_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sub_status', models.CharField(choices=[('Approved Pending', 'Approved Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved Pending', max_length=55)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.employee')),
            ],
        ),
    ]
