# Generated by Django 5.1.4 on 2025-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('business_unit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('sub_department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cost_center', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('late_by', models.DurationField(blank=True, null=True)),
                ('early_by', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('effective_hours', models.DurationField(blank=True, null=True)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('over_time', models.DurationField(blank=True, null=True)),
                ('total_short_hours_effective', models.DurationField(blank=True, null=True)),
                ('total_short_hours_gross', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
