# Generated by Django 5.1.4 on 2025-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0012_employeedata_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='status',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='day',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend')], default='Weekday', max_length=50),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='shift_out',
            field=models.CharField(default='6:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='shift_time',
            field=models.CharField(default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='mode_of_work',
            field=models.CharField(choices=[('work-from-home', 'Work-from-home'), ('work-from-office', 'Work-from-office')], default='work-from-office', max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='sub_status',
            field=models.CharField(choices=[('working', 'Working'), ('On Leave', 'On Leave')], default='Present', max_length=55),
        ),
    ]
