# Generated by Django 5.1.4 on 2025-01-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0014_remove_timesheet_remarks_remove_timesheet_shift_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.company'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.company'),
        ),
    ]
